language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq python-opencv libopencv-dev
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq python-matplotlib
  - pip install -r requirements.txt

script:
  - python setup.py test
