# Params for SIFT extraction.
edge_threshold: 10          # Filters on DoG scale space curvature size. Larger value gives more features.
peak_threshold: 0.01        # Filters on DoG scale space peak size. Smaller value gives more features.

# Params for principal component analysis.
descriptor_weight: 0.725    # Weight of the descriptors with respect to the L2 norm of the combined feature vector.
neutral_factor: 0.8         # Factor of the neutral vector to be subtracted in the neutral vector subtraction PCA.
feature_mode: ALL           # Features to be used. Possible values: ALL, COLORS, DESCRIPTORS

# Params for feature vector distance measuring.
pc_projection_count: 30     # Number of principal component projections used.
closest_group: 0.3          # Proportion of the images to be included in the closest group. In interval [0, 1].
representative: 0.05        # Proportion of the images to be determined as representative. Smaller than closest group.

# Params for determining all structures using k-means.
clusters: 8                 # Number of cluster centroids.
runs: 500                   # Number of times to run the k-means algorithm. The run with lowest distortion is chosen.
iterations: 100             # Number of iterations for each run of k-means.

# General params.
processes: 8                # Number of parallel processes for downloading and extraction.
collection_count: 100       # Size of collection. Number of images to be downloaded. Maximum is 500.

# Plot params.
save_plot: false            # Boolean specifying if plots should be saved to file.
image_dimension: 100        # Dimension of the longest side of images in plots.
columns: 10                 # Number of columns in result plots.
ticks: false                # Boolean specifying if the principal component projection plots should have ticks.
pc_plots: [[2, 3], [4, 5]]  # Principal components for which to plot the projections against. List of principal component pairs.